default: &default
  # Database configuration
  DB_PORT: "5432"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  DB_DATABASE: "database name"
  DB_USERNAME: "database username"
  DB_PASSWORD: "database password"
  # Mailer configuration
  MAILER_SMTP_ADDRESS: "smtp email address"
  MAILER_SMTP_DOMAIN: "smtp email domain"
  MAILER_SMTP_PORT: "587"
  MAILER_SMTP_USER_NAME: "smtp email username"
  MAILER_SMTP_PASSWORD: "smtp email password"
  # GeoCoder configuration (developer.here.com)
  HERE_API_KEY: "your here api key"
  SECRET_KEY_BASE: "secret_key_base"
  PINBAL_SOLICITANTE_IDENTIFICADOR_SOLICITANTE: "S0711001H"
  PINBAL_SOLICITANTE_NOMBRE_SOLICITANTE: "CONSELL INSULAR DE MALLORCA"
  PINBAL_SOLICITANTE_UNIDAD_TRAMITADORA: "DIRECCIO INSULAR DE PARTICIPACIO"
  PINBAL_SOLICITANTE_COD_PROCEDIMIENTO: "CODSVDR_GBA_20121107"
  PINBAL_SOLICITANTE_NOMBRE_PROCEDIMIENTO: "PRUEBAS DE INTEGRACION PARA GOBIERNO DE BALEARES"
  PINBAL_SOLICITANTE_NOMBRE_COMPLETO_FUNCIONARIO: "Funcionari Consell"
  PINBAL_SOLICITANTE_NIF_FUNCIONARIO: "00000000T"
  PINBAL_SOLICITANTE_ID_EXPEDIENTE: "EXP/18122012"
  PINBAL_SOLICITANTE_FINALIDAD: "Poder participar en la plataforma de participación del Consell de Mallorca"
  PINBAL_SOLICITANTE_CONSENTIMIENTO: "Si"

development:
  <<: *default

integration:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

staging:
  <<: *default

production:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
